# fly.toml app configuration file
app = "kent-ai-agent"
primary_region = "iad"

[build]

[env]
  PORT = "8000"
  PYTHONPATH = "/app/src"
  DATABASE_PATH = "/app/data/conversations.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[mounts]
  source = "kent_data"
  destination = "/app/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "python -c 'import sqlite3; conn = sqlite3.connect(\"/app/data/conversations.db\"); conn.execute(\"CREATE TABLE IF NOT EXISTS conversations (id INTEGER PRIMARY KEY, session_id TEXT, user_message TEXT, agent_response TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP)\"); conn.execute(\"CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, last_active DATETIME DEFAULT CURRENT_TIMESTAMP)\"); conn.commit(); conn.close()'"